### PR TITLE
Exclude NaNs to fix get_sub_corr()

### PR DESCRIPTION
**Pull request by ngreenstein**

### CODE REVIEW

**Comment by ngreenstein** [comment]
Not sure if this is exactly how we want to go about this, but I think we need to do it somehow -- `get_corr()` does something similar (line ~82), and so does `get_sub_mse()` (line ~129).

**Comment by ljchang** [comment]
Looks like it is just a failing test.  Can you see the travisci output?  If not we should figure out how to get you added.

**Comment by ngreenstein** [comment]
Okay, I got travisci access and I'm a little confused why the test is failed. The one that failed was using `data='test'`, which is a path this commit doesn't change at all -- it only impacts `data='all'`, which is passing. I re-ran the build and things look clean.

**Comment by ngreenstein** [comment]
Update: looks like the same issue still exists when the `data` is `test` or `train`. I'll look at a solution that applies to those paths as well.

**Comment by ngreenstein** [comment]
See #24  for a broader solution

**Pull request closed without merging**
